### ISSUE TITLE
Installation Fails w/ Contextify Error

### ISSUE THREAD

**Issue by ptwohig** [briangonzalez/craigslist-scout#2]
Trying to install, but it seems that there is a problem with a dependency.  I know very little about NodeJS, but it seems that this issue is with Contextify, which has since fixed the issue.

`
npm WARN deprecated lodash-node@2.4.1: This package has been discontinued in favor of lodash@^4.0.0
npm WARN engine hawk@3.1.3: wanted: {"node":">=0.10.32"} (current: {"node":"0.10.25","npm":"1.4.21"})
|
  contextify@0.1.15 install /usr/local/lib/node_modules/craigslistscout/node_modules/jsdom/node_modules/contextify
  node-gyp rebuild

/bin/sh: 1: node: not found
gyp: Call to 'node -e "require('nan')"' returned exit status 127. while trying to load binding.gyp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/share/node-gyp/lib/configure.js:344:16)
gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:797:12)
gyp ERR! System Linux 4.2.0-16-generic
gyp ERR! command "nodejs" "/usr/bin/node-gyp" "rebuild"
gyp ERR! cwd /usr/local/lib/node_modules/craigslist-scout/node_modules/jsdom/node_modules/contextify
gyp ERR! node -v v0.10.25
gyp ERR! node-gyp -v v0.12.2
gyp ERR! not ok
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian
npm ERR! error rolling back Error: ENOTEMPTY, rmdir '/usr/local/lib/node_modules/craigslist-scout/node_modules/jsdom/node_modules/cssstyle/lib/properties'
npm ERR! error rolling back  jsdom@1.0.3 { [Error: ENOTEMPTY, rmdir '/usr/local/lib/node_modules/craigslist-scout/node_modules/jsdom/node_modules/cssstyle/lib/prop
erties']
npm ERR! error rolling back   errno: 53,
npm ERR! error rolling back   code: 'ENOTEMPTY',
npm ERR! error rolling back   path: '/usr/local/lib/node_modules/craigslist-scout/node_modules/jsdom/node_modules/cssstyle/lib/properties' }
npm ERR! tar.unpack untar error /home/ptwohig/.npm/hawk/3.1.3/package.tgz
npm ERR! tar.unpack untar error /home/ptwohig/.npm/json-schema/0.2.2/package.tgz
npm ERR! error rolling back Error: ENOTEMPTY, rmdir '/usr/local/lib/node_modules/craigslist-scout/node_modules/lodash-node/modern/internals'
npm ERR! error rolling back  craigslist-scout@0.1.1 { [Error: ENOTEMPTY, rmdir '/usr/local/lib/node_modules/craigslist-scout/node_modules/lodash-node/modern/intern
als']
npm ERR! error rolling back   errno: 53,
npm ERR! error rolling back   code: 'ENOTEMPTY',
npm ERR! error rolling back   path: '/usr/local/lib/node_modules/craigslist-scout/node_modules/lodash-node/modern/internals' }
npm ERR! contextify@0.1.15 install: `node-gyp rebuild`
npm ERR! You can get their info via:
npm ERR!     npm owner ls contextify
npm ERR! There is likely additional logging output above.
npm ERR! System Linux 4.2.0-16-generic
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install" "craigslist-scout" "-g"
npm ERR! cwd /home/ptwohig
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.4.21
npm ERR! code ELIFECYCLE
npm ERR! tar.unpack untar error /home/ptwohig/.npm/lowdb/0.4.2/package.tgz
npm ERR! tar.unpack untar error /home/ptwohig/.npm/cssstyle/0.2.34/package.tgz
npm ERR! tar.unpack untar error /home/ptwohig/.npm/jsonpointer/2.0.0/package.tgz
npm ERR! tar.unpack untar error /home/ptwohig/.npm/generate-function/2.0.0/package.tgz
npm ERR! tar.unpack untar error /home/ptwohig/.npm/generate-object-property/1.2.0/package.tgz
npm ERR! tar.unpack untar error /home/ptwohig/.npm/jodid25519/1.0.2/package.tgz
npm WARN optional dep failed, continuing ecc-jsbn@0.1.1
npm ERR! tar.unpack untar error /home/ptwohig/.npm/jsbn/0.1.0/package.tgz
npm WARN optional dep failed, continuing jodid25519@1.0.2
npm ERR! tar.unpack untar error /home/ptwohig/.npm/asn1/0.2.3/package.tgz
npm ERR! error rolling back Error: ENOTEMPTY, rmdir '/usr/local/lib/node_modules/craigslist-scout/node_modules/jsdom/node_modules/request/node_modules'
npm ERR! error rolling back  request@2.69.0 { [Error: ENOTEMPTY, rmdir '/usr/local/lib/node_modules/craigslist-scout/node_modules/jsdom/node_modules/request/node_modules']
npm ERR! error rolling back   errno: 53,
npm ERR! error rolling back   code: 'ENOTEMPTY',
npm ERR! error rolling back   path: '/usr/local/lib/node_modules/craigslist-scout/node_modules/jsdom/node_modules/request/node_modules' }
npm WARN optional dep failed, continuing jsbn@0.1.0
npm ERR! tar.unpack untar error /home/ptwohig/.npm/dashdash/1.12.2/package.tgz
npm ERR! error rolling back Error: ENOTEMPTY, rmdir '/usr/local/lib/node_modules/craigslist-scout/node_modules/jsdom/node_modules/request/node_modules/har-validator/node_modules/is-my-json-valid/node_modules/xtend'
npm ERR! error rolling back  har-validator@2.0.6 { [Error: ENOTEMPTY, rmdir '/usr/local/lib/node_modules/craigslist-scout/node_modules/jsdom/node_modules/request/node_modules/har-validator/node_modules/is-my-json-valid/node_modules/xtend']
npm ERR! error rolling back   errno: 53,
npm ERR! error rolling back   code: 'ENOTEMPTY',
npm ERR! error rolling back   path: '/usr/local/lib/node_modules/craigslist-scout/node_modules/jsdom/node_modules/request/node_modules/har-validator/node_modules/is-my-json-valid/node_modules/xtend' }
npm ERR! tar.unpack untar error /home/ptwohig/.npm/tweetnacl/0.13.3/package.tgz
npm WARN optional dep failed, continuing tweetnacl@0.13.3
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     /home/ptwohig/npm-debug.log
npm ERR! not ok code 0

`

**Comment by briangonzalez** [comment]
@ptwohig 

Upgraded jsdom in this commit: 3c62d306c848bd1d0536d6b19912cb76f5508515
